apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: panda1920/complex-worker
      ports:
        - containerPort: 12312
