version: 2.1

executors:
  my-node:
    docker:
      - image: circleci/node:12.2

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2

jobs:
  test-frontend:
    executor: my-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-frontend-{{ checksum "./frontend/package-lock.json" }}
            - v1-frontend
      - run:
          name: Installing dependencies
          command: |
            cd ./frontend
            npm install
      - run:
          name: Run tests
          command: |
            cd ./frontend
            npm run test
      - save_cache:
          when: on_success
          key: v1-frontend-{{ checksum "./frontend/package-lock.json" }}
          paths:
            - "./frontend/node_modules"

  deploy-frontend:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          checkout: true
          path: './frontend'
          extra-build-args: '--pull --no-cache'
          repo: udemy-frontend

  complex-test:
    executor: my-node
    steps:
      - checkout
      - restore_cache:
          name: Restoring cache for client
          keys:
            - v1-complex-{{ checksum "./complex/client/package-lock.json" }}-{{ checksum "./complex/server/package-lock.json" }}-{{ checksum "./complex/worker/package-lock.json" }}
            - v1-complex
      - run:
          name: Installing dependencies
          command: |
            cd ./complex/client
            npm install
            cd ./complex/server
            npm install
            cd ./complex/worker
            npm install
      - run:
          name: Run tests
          command: |
            cd ./complex/client
            npm run test
      - save_cache:
          name: Saving cache
          when: on_success
          key: v1-complex-{{ checksum "./complex/client/package-lock.json" }}-{{ checksum "./complex/server/package-lock.json" }}-{{ checksum "./complex/worker/package-lock.json" }}
          paths:
            - "./complex/client/node_modules"
            - "./complex/server/node_modules"
            - "./complex/worker/node_modules"

  complex-build:
    executor: my-node
    environment:
      IMAGENAME_CLIENT: panda1920/complex/client
      IMAGENAME_SERVER: panda1920/complex/server
      IMAGENAME_WORKER: panda1920/complex/worker
      IMAGENAME_NGINX: panda1920/complex/nginx
    steps:
      - checkout
      - restore_cache:
          name: Restoring cache
          keys:
            - v1-complex-{{ checksum "./complex/client/package-lock.json" }}-{{ checksum "./complex/server/package-lock.json" }}-{{ checksum "./complex/worker/package-lock.json" }}
            - v1-complex
      - run:
          name: Installing dependencies
          command: |
            cd ./complex/client
            npm install
            cd ./complex/server
            npm install
            cd ./complex/worker
            npm install
      - run:
          name: Build images
          command: |
            cd ./complex/client
            docker build -t $IMAGENAME_CLIENT --no-cache --pull .
            cd ./complex/server
            docker build -t $IMAGENAME_SERVER --no-cache --pull .
            cd ./complex/worker
            docker build -t $IMAGENAME_WORKER --no-cache --pull .
            cd ./complex/nginx
            docker build -t $IMAGENAME_NGINX --no-cache --pull .
      - run:
          name: Send images to dockerhub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGENAME_CLIENT
            docker push $IMAGENAME_SERVER
            docker push $IMAGENAME_WORKER
            docker push $IMAGENAME_NGINX

workflows:
  # build-and-test:
  #   jobs:
  #     - test-frontend
  #     - deploy-frontend:
  #         requires:
  #           - test-frontend
  #         context: AWS
  complex-build-and-test:
    jobs:
      - complex-test
      - complex-build:
          requires:
            - complex-test
