version: 2.1

executors:
  my-node:
    docker:
      - image: circleci/node:12.2

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2

jobs:
  test-frontend:
    executor: my-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-frontend-{{ checksum "./frontend/package-lock.json" }}
            - v1-frontend
      - run:
          name: Installing dependencies
          command: |
            cd ./frontend
            npm install
      - run:
          name: Run tests
          command: |
            cd ./frontend
            npm run test
      - save_cache:
          when: on_success
          key: v1-frontend-{{ checksum "./frontend/package-lock.json" }}
          paths:
            - "./frontend/node_modules"

  deploy-frontend:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          account-url: $AWS_ECR_ACCOUNT_URL
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION
          checkout: true
          path: './frontend'
          extra-build-args: '--pull --no-cache'
          repo: udemy-frontend

workflows:
  build-and-test:
    jobs:
      - test-frontend
      - deploy-frontend:
          requires:
            - test-frontend
          context: AWS
